######################################################################
# Automatically generated by qmake (2.01a) ??  29 17:08:32 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stickerwindow.h note.h
SOURCES += main.cpp stickerwindow.cpp
