######################################################################
# Automatically generated by qmake (2.01a) ??  29 17:08:32 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT +=xml
CONFIG +=debug

# Input
HEADERS += stickerwindow.h note.h storagedevice.h localdiskstorage.h
SOURCES += main.cpp stickerwindow.cpp note.cpp
